name: CosmicAuctionHouse
version: '${project.version}'
main: me.panda.cosmicauctionhouse.CosmicAuctionHouse
api-version: '1.20'
author: Panda19
depend:
  - Vault
commands:
  ah:
    description: "Opens up the auctionhouse GUI"
    aliases:
      - AuctionHouse